### ISSUE TITLE
fails on macos

### ISSUE THREAD

**Issue by djsmentya** [tangledpath/ruby-fann#13]
i want to train  network to sum two numbers but i have an error with this code

```
data = [] 
100.times { data << [rand.round(2), rand.round(2)]}
train = RubyFann::TrainData.new(:inputs=> data, :desired_outputs=> data.map{|e| e.inject(:+)})
```

error output:

https://gist.github.com/anonymous/c8ca1b846ed68269bdf2

**Comment by inspire22** [comment]
both input and outputs need to be normalized to between -1 and 1

**Comment by djsmentya** [comment]
@inspire22 thanks
