### ISSUE TITLE
Is this gem still maintained?

### ISSUE THREAD

**Issue by Ch4s3** [tangledpath/ruby-fann#14]
Is this gem maintained or open to new maintainers?

**Comment by agarie** [comment]
This is a good question. If @tangledpath is OK with it, I'd like to maintain this gem under [SciRuby](https://github.com/sciruby/).

**Comment by Ch4s3** [comment]
@agarie That would be awesome! I love what SciRuby is doing!

**Comment by gbuesing** [comment]
@agarie would be great to see this gem maintained by the SciRuby community. Looks like the maintainer hasn't committed any code or responded to any issues on this project since 2013, so I assume it's fine to go ahead and fork it, and just push out gem updates under a different name (maybe just "fann")?

**Comment by agarie** [comment]
That's a good idea. However, I'll wait until Google Summer of Code ends (in approximately 1 month) before trying to maintain another project, as there are lots of work right now. :P

**Comment by groe** [comment]
@agarie  Any updates on this?

**Comment by bararchy** [comment]
@agarie I will also love to hear about this :)

**Comment by Ch4s3** [comment]
:+1:

**Comment by jjgh** [comment]
:up:

**Comment by djones** [comment]
Would love to see this project maintained.

**Comment by bararchy** [comment]
BTW , if any of you uses Crystal , then we got this shard going https://github.com/bararchy/crystal-fann.

**Comment by jjgh** [comment]
@agarie do you have any updates on this?

**Comment by bararchy** [comment]
TBH the real issue is that the FANN project is half dead, the original maintainer has not responded there for about 2 years, so there is so much this repo can do :\
