### ISSUE TITLE
One class classification using Ruby Fann? 

### ISSUE THREAD

**Issue by pbssubhash** [tangledpath/ruby-fann#19]
Hey, Just wondering if it's possible to use this gem for outlier classification or the one class classification wherein I only have data for positive or negative and I want to classify the coming data if it belongs to the group or not.

If not, any such in Ruby? 

Any help is appreciated.

**Comment by git-steven** [comment]
Yes, just use `1.0` for `true` and `0.0` for `false` (or `-1.0` for symmetric activation functions)
